<?php
$this->headLink()->appendStylesheet($this->basePath('/web-assets/css/promociones.css'));
?>

<div class="pizzas">
    <div class="menu">
        <button class="boton-inicio boton-menu">
            <div class="logo-menu"></div>
        </button>
        <button class="boton-facebook boton-menu">
            <div class="facebook"></div>
        </button>
        <button class="boton-facebook boton-menu">
            <div class="whatsapp"></div>
        </button>
        <button class="boton-facebook boton-menu">
            <div class="instagram"></div>
        </button>
        <button class="boton-facebook boton-menu">
            <div class="maps"></div>
        </button>
    </div>
    <div class="titulo">
        <div class="fondo-boton">
        </div>
        <span class="pizzas-1">
            Promociones
        </span>
    </div>
    <div class="contenido">
        <div class="promo1">
        </div>
        <img class="separador" src="<?= $this->basePath('/web-assets/vectors/line2_x2.svg') ?>" />
        <div class="promo2">
        </div>
    </div>
</div>

<script>
    $(document).ready(function() {
        $(".boton-inicio").click(function() {
            window.location.href = '<?= $this->url('web-home') ?>';
        });
        $(".facebook").click(function() {
            window.location.href = 'http://www.facebook.com/Luigispizzaarica1';
        });
        $(".whatsapp").click(function() {
            window.location.href = 'https://api.whatsapp.com/send?phone=++56972461072&text=Hola!%20Me%20gustaria%20hacer%20un%20pedido!';
        });
        $(".instagram").click(function() {
            window.location.href = 'https://www.instagram.com/luigisarica';
        });
        $(".maps").click(function() {
            window.location.href = "https://www.google.cl/maps/dir//Luigi's+Pizza+-+Conrado+R%C3%ADos+1593,+1001085+Arica,+Arica+y+Parinacota/@-18.4856886,-70.3071732,15.25z/data=!4m8!4m7!1m0!1m5!1m1!1s0x915aa9c8e55511e9:0xdda7bced3817eaa5!2m2!1d-70.2986061!2d-18.4845687?entry=ttu";
        });
    });
</script>