<?= $this->doctype() ?>

<html lang="es">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= $this->headTitle("Luigi's Pizza")->setSeparator(' - ')->setAutoEscape(false) ?>

    <!-- Open Graph / Facebook -->
    <meta property="og:type" content="Carta Digital">
    <meta property="og:url" content="https://www.luigis.cl/">
    <meta property="og:title" content="Luigi's Pizza">
    <meta property="og:description" content="Carta Digital, ¿Que pizza deseas hoy? 🍕👋">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lalezar:wght@400&display=swap" rel="stylesheet">

    <?= $this->headLink() ?>
    <?= $this->headStyle() ?>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <?= $this->headScript() ?>
</head>

<body>
    <?= $this->content ?>

    <?= $this->inlineScript() ?>
</body>

</html>