<?= $this->doctype() ?>

<html lang="en">

<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Laminas MVC Skeleton')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            padding-top: 4.5rem;
        }

        .bg-laminas {
            background-color: #0c0;
        }

        /* Placeholder color, usually Laminas uses its own CSS */
    </style>

    <?= $this->headLink() ?>

    <!-- Scripts -->
    <?= $this->headScript() ?>
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-success">
        <div class="container">
            <a class="navbar-brand" href="<?= $this->url('home') ?>">
                <!-- <img src="<?= $this->basePath('img/laminas-logo.svg') ?>" height="28" alt="Laminas MVC Skeleton"> -->
                Laminas Skeleton
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="<?= $this->url('home') ?>">Home</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <main class="container">
        <?= $this->content ?>
    </main>

    <footer class="container">
        <hr>
        <p>&copy; <?= date('Y') ?> <a href="https://getlaminas.org/">Laminas Project</a> a Series of LF Projects, LLC.</p>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <?= $this->inlineScript() ?>
</body>

</html>