<div class="jumbotron">
    <h1 class="display-4">Welcome to <span class="text-success">Laminas MVC</span></h1>
    <p>Congratulations! You have successfully installed the <a href="https://github.com/laminas/laminas-mvc-skeleton" target="_blank" rel="noopener noreferrer">Laminas MVC Skeleton</a> application.</p>
    <hr class="my-4">
    <p>This skeleton application usually ships with the following modules:</p>
    <ul>
        <li><a href="https://github.com/laminas/laminas-mvc" target="_blank" rel="noopener noreferrer">laminas-mvc</a></li>
        <li><a href="https://github.com/laminas/laminas-modulemanager" target="_blank" rel="noopener noreferrer">laminas-modulemanager</a></li>
        <li><a href="https://github.com/laminas/laminas-validator" target="_blank" rel="noopener noreferrer">laminas-validator</a></li>
        <li><a href="https://github.com/laminas/laminas-inputfilter" target="_blank" rel="noopener noreferrer">laminas-inputfilter</a></li>
    </ul>

    <p>You can follow the development of Laminas MVC at the <a href="https://github.com/laminas" target="_blank" rel="noopener noreferrer">Laminas GitHub organization</a>.</p>

    <a class="btn btn-success btn-lg" href="https://github.com/laminas/laminas-mvc-skeleton" target="_blank" role="button">Laminas MVC Skeleton on GitHub &raquo;</a>
</div>